version: '2.1'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wp-app
    hostname: wp-app
    container_name: wp-app
    depends_on:
      wp-db:
        condition: service_started
      wp-redis:
        condition: service_started

  wp-db:
    build:
      context: ./.docker
      dockerfile: Dockerfile.mysql
    image: wp-db
    hostname: wp-db
    container_name: wp-db

  wp-redis:
    build:
      context: ./.docker
      dockerfile: Dockerfile.redis
    image: wp-redis
    hostname: wp-redis
    container_name: wp-redis

