FROM centos
EXPOSE 3306
### Add package Maria-db
ADD /config /

RUN yum update -y && yum install -y epel-release && \
    yum install -y MariaDB-server supervisor

ADD db_access.sh .

### Supervisor is not start

CMD ["supervisord", "-c", "/etc/supervisord.conf"]
